### ISSUE TITLE
ga bisa konek

### ISSUE THREAD

**Issue by ondrong** [akbaraditamasp/guwa-lite#4]
salam dan terima kasih atas sourcenya mas,
apakah bisa di bantu dengan kendala pada waktu habis scan barcode tapi ga bisa sync 

log nya : 

`[22:52:32.751] FATAL (whatsapp-backend/11286): "uncaughtException" detected
    Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'queryExists')
        at __puppeteer_evaluation_script__:25:69
        at ExecutionContext._evaluateInternal (/Users/macbookpro/Documents/node/wa_server_guwa-lite/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at ExecutionContext.evaluate (/Users/macbookpro/Documents/node/wa_server_guwa-lite/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
        at Client.initialize (/Users/macbookpro/Documents/node/wa_server_guwa-lite/node_modules/whatsapp-web.js/src/Client.js:267:9)
[22:52:32.762] WARN (whatsapp-backend/11286): pino.final with prettyPrint does not support flushing
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'queryExists')
    at __puppeteer_evaluation_script__:25:69
    at ExecutionContext._evaluateInternal (/Users/macbookpro/Documents/node/wa_server_guwa-lite/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/Users/macbookpro/Documents/node/wa_server_guwa-lite/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.initialize (/Users/macbookpro/Documents/node/wa_server_guwa-lite/node_modules/whatsapp-web.js/src/Client.js:267:9)
[ warn ]  Underlying HTTP server died with "1 code"`

terima kasih

**Comment by akbaraditamasp** [comment]
Ini sepertinya error dari library whatsapp-web.js nya. selagi menunggu update, sementara ganti dulu Line 28 pada file node_modules/whatsapp-web.js/src/util/Injected.js dengan ini

```
window.Store.QueryExist = window.mR.findModule('queryExists')[0] ? window.mR.findModule('queryExists')[0].queryExists : window.mR.findModule('queryExist')[0].queryWidExists;
```

**Comment by ondrong** [comment]
aaasiap.
terima kasih atas support nya.

**Comment by ondrong** [comment]
btw DANA send,
mohon maaf kl terlalu sedikit.

**Comment by ondrong** [comment]
laporan sudah jalan mas,

untuk API nya apa ada end points contoh nya ya ?

terima kasih

**Comment by akbaraditamasp** [comment]
> btw DANA send, mohon maaf kl terlalu sedikit.

Thanks mas donasinya. Sorry baru bales, kemarin masih sibuk sama kerjaan kantor

**Comment by akbaraditamasp** [comment]
> laporan sudah jalan mas,
> 
> untuk API nya apa ada end points contoh nya ya ?
> 
> terima kasih

Next saya bikinkan dokumentasinya juga deh, sementara bisa diliat di routenya ada routing untuk send whatsappnya
